  version: "3"

  tasks:
    generate:
      aliases:
        - gen
      desc: "Easy"
      cmds:
        - protoc -I proto proto/validate/*.proto proto/sso/*.proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative --validate_out="lang=go:./gen"
